version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '06:00'
      timezone: 'UTC'
    open-pull-requests-limit: 10
    commit-message:
      prefix: 'deps'
      prefix-development: 'deps-dev'
      include: 'scope'
    labels:
      - 'dependencies'
      - 'automated'
    # Group updates for better management
    groups:
      nodejs-updates:
        patterns:
          - '@types/node'
        update-types:
          - 'minor'
          - 'patch'
          - 'major'
      dynatrace-sdk:
        patterns:
          - '@dynatrace-sdk/*'
        update-types:
          - 'minor'
          - 'patch'
      dev-dependencies:
        dependency-type: 'development'
        update-types:
          - 'minor'
          - 'patch'
        exclude-patterns:
          - '@types/node'
      major-updates:
        update-types:
          - 'major'
        exclude-patterns:
          - '@types/node'
    # Ignore specific packages if needed
    ignore:
      # Ignore major version updates for core dependencies to avoid breaking changes
      - dependency-name: '@modelcontextprotocol/sdk'
        update-types: ['version-update:semver-major']
      - dependency-name: 'dt-app'
        update-types: ['version-update:semver-major']
      # Node.js version policy: Only allow LTS versions and be conservative about upgrades
      # Current: Node.js 22 (LTS until October 2025)
      # Ignore non-LTS Node.js versions (odd-numbered major versions)
      - dependency-name: 'node'
        versions: ['23.x', '25.x', '27.x', '29.x', '31.x', '33.x']
      - dependency-name: '@types/node'
        versions: ['23.x', '25.x', '27.x', '29.x', '31.x', '33.x']
      # Allow future LTS versions but ignore immediate next major (24.x) until closer to EOL
      # This provides a buffer period to test compatibility before upgrading, and avoids
      # having a new NodeJS 24 PR opened every couple of days
      - dependency-name: 'node'
        versions: ['24.x']
      - dependency-name: '@types/node'
        versions: ['24.x']

  # Enable version updates for GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '06:00'
      timezone: 'UTC'
    open-pull-requests-limit: 5
    commit-message:
      prefix: 'ci'
      include: 'scope'
    labels:
      - 'github-actions'
      - 'automated'

  # Enable version updates for Docker
  - package-ecosystem: 'docker'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '06:00'
      timezone: 'UTC'
    open-pull-requests-limit: 3
    commit-message:
      prefix: 'docker'
      include: 'scope'
    labels:
      - 'docker'
      - 'automated'
    # Group Node.js Docker updates separately
    groups:
      nodejs-docker-updates:
        patterns:
          - 'node'
        update-types:
          - 'minor'
          - 'patch'
          - 'major'
    # Node.js version policy for Docker: Only use LTS versions and be conservative about upgrades
    ignore:
      # Ignore non-LTS Node.js versions in Docker images
      - dependency-name: 'node'
        versions: ['23.x', '25.x', '27.x', '29.x', '31.x', '33.x']
      # Allow future LTS versions but ignore immediate next major (24.x) until closer to EOL
      - dependency-name: 'node'
        versions: ['24.x']
