version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '06:00'
      timezone: 'UTC'
    open-pull-requests-limit: 10
    reviewers:
      - 'dynatrace-oss/dynatrace-mcp-maintainers'
    assignees:
      - 'dynatrace-oss/dynatrace-mcp-maintainers'
    commit-message:
      prefix: 'deps'
      prefix-development: 'deps-dev'
      include: 'scope'
    labels:
      - 'dependencies'
      - 'automated'
    # Group updates for better management
    groups:
      dynatrace-sdk:
        patterns:
          - '@dynatrace-sdk/*'
        update-types:
          - 'minor'
          - 'patch'
      dev-dependencies:
        dependency-type: 'development'
        update-types:
          - 'minor'
          - 'patch'
      major-updates:
        update-types:
          - 'major'
    # Ignore specific packages if needed
    ignore:
      # Ignore major version updates for core dependencies to avoid breaking changes
      - dependency-name: '@modelcontextprotocol/sdk'
        update-types: ['version-update:semver-major']
      - dependency-name: 'dt-app'
        update-types: ['version-update:semver-major']

  # Enable version updates for GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '06:00'
      timezone: 'UTC'
    open-pull-requests-limit: 5
    reviewers:
      - 'dynatrace-oss/dynatrace-mcp-maintainers'
    assignees:
      - 'dynatrace-oss/dynatrace-mcp-maintainers'
    commit-message:
      prefix: 'ci'
      include: 'scope'
    labels:
      - 'github-actions'
      - 'automated'

  # Enable version updates for Docker
  - package-ecosystem: 'docker'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '06:00'
      timezone: 'UTC'
    open-pull-requests-limit: 3
    reviewers:
      - 'dynatrace-oss/dynatrace-mcp-maintainers'
    assignees:
      - 'dynatrace-oss/dynatrace-mcp-maintainers'
    commit-message:
      prefix: 'docker'
      include: 'scope'
    labels:
      - 'docker'
      - 'automated'
