name: Publish to MCP Registry

on:
  workflow_dispatch: # Allows manual re-triggering without pushing a new tag

permissions:
  id-token: write # Required for GitHub OIDC login to MCP Registry

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      # From https://github.com/modelcontextprotocol/registry/blob/main/docs/guides/publishing/github-actions.md
      - name: Install MCP Publisher
        run: |
          curl -L "https://github.com/modelcontextprotocol/registry/releases/latest/download/mcp-publisher_$(uname -s | tr '[:upper:]' '[:lower:]')_$(uname -m | sed 's/x86_64/amd64/;s/aarch64/arm64/').tar.gz" | tar xz mcp-publisher

      # Login to GitHub - apparently this works out of the box with GH Workflows
      - name: Login to MCP Registry
        run: ./mcp-publisher login github-oidc

      # Publish the package to the MCP Registry
      - name: Publish to MCP Registry
        run: ./mcp-publisher publish
